### ISSUE TITLE
Event tracking is querying a span of blocks longer than maximum allowed range

### ISSUE THREAD

**Issue by polymorpher** [harmony-one/pump.fun.backend#1]
See in https://github.com/harmony-one/pump.fun.backend/blob/404cf15d2dbdaf45da7e7012498acc1a2a882d67/src/indexer/indexer.service.ts#L298 and related calls below. I believe web3 would make a single RPC call under the hood to query the logs from this contract and decode the events. However, in Harmony RPC code, if the differences between the start and ending block is more than 1024, the RPC would respond with an error.

Moreover, only archive node can be queried for older block numbers.

The loop might need to ensure each call is less than 1024 blocks and the RPC node is archive node

**Comment by ArtemKolodko** [comment]
1) Difference between fromBlock and toBlock is always <= 1000 blocks (limited by this.blocksIndexingRange constant):
```
private readonly blocksIndexingRange = 1000
...
toBlock = fromBlock + this.blocksIndexingRange - 1
```

Sources:
https://github.com/harmony-one/pump.fun.backend/blob/main/src/indexer/indexer.service.ts#L345

2) Service is connected to the Archive RPC node by default:
https://github.com/harmony-one/pump.fun.backend/blob/main/src/config/index.ts#L49

But I agree, some Archival node checks can be added on service start up if we have a plans to launch it in different chain or testnet

**Comment by polymorpher** [comment]
Okay
