### ISSUE TITLE
Possible stack and memory overflow in non-tail recursion 

### ISSUE THREAD

**Issue by polymorpher** [harmony-one/pump.fun.backend#2]
See https://github.com/harmony-one/pump.fun.backend/blob/404cf15d2dbdaf45da7e7012498acc1a2a882d67/src/indexer/indexer.service.ts#L383

and discussion and solution in https://stackoverflow.com/questions/49165805/node-js-are-there-optimizations-for-tail-calls-in-async-functions

**Comment by ArtemKolodko** [comment]
Thanks! Fixed:
https://github.com/harmony-one/pump.fun.backend/commit/66cafdd423e42eef0974705f4c52460ff0480c06
